theme: jekyll-theme-minimal
title: Michael Knudson
description: I earned my PhD in Materials Science and Engineering from Northwestern University and then worked as a process engineer at Intel. I am now pursuing my interest in data science and machine learning.
logo: /images/profile_pic.png
